# Tracker config BASE
# This file will be used to create the tracker config for each video
# of the dataset. E.g., 
# One video is in: /bulk/data/processed/face_recordings/2/bite_lower_lip/video.mp4
# But this config file has to have the following path in actor key:
# actor: './bulk/data/processed/face_recordings/2/bite_lower_lip/'
# But there are many subfolders inside face_recordings/2 and also in 
# face_recordings/3, etc.

actor: './bulk/data/processed/face_recordings/'
save_folder: './bulk/data/interim/face_recordings/Metrical-Tracker/'

# This will treat this config as a base_config and run a Tracker instance
# for each actor/class/video.mp4 found in the actor path
is_base_config: true

# This will just print the configs extracted from the base_config as debug
# and won't run a Tracker instance
test_run: true

# Rest of the Tracker config
optimize_shape: true
optimize_jaw: true
begin_frames: 1
fps: 30
keyframes: [ 0, 1 ]